modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "stickykeys"
version = "${version}"
displayName = "StickyKeys"
authors = "MelnCat"
logoFile="assets/stickykeys/icon.png"
description = '''
Hold keys down without needing to do it yourself.
'''
displayTest="IGNORE_ALL_VERSION"
#logoFile = ""

[[dependencies.stickykeys]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "(,3.4.2+1.20.1-forge]"
ordering = "AFTER"
side = "BOTH"
