modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "stickykeys"
version = "${version}"
displayName = "StickyKeys"
authors = "MelnCat"
logoFile="assets/stickykeys/icon.png"
description = '''
Hold keys down without needing to do it yourself.
'''
displayTest="IGNORE_ALL_VERSION"
#logoFile = ""

[[dependencies.stickykeys]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.stickykeys]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "(3.5.0,]"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stickykeys.mixins.json"

[[mixins]]
config = "stickykeys.neoforge.mixins.json"